name: Pac-man Retro Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pac-man Animation
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: RicardoNevees
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_extending: yes
          # Esta é a configuração que gera o labirinto clássico
          config_order: isocalendar
          output_action: commit
          committer_gist: ${{ github.repository_owner }}/pacman-output
          filename: pacman-contribution-graph.svg
