name: Generate Pacman Retro

on:
  schedule: # Executa a cada 24 horas
    - cron: "0 */24 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate-pacman-retro-svg
        uses: jasonlong/generate-github-contribution-grid-snake@v1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg?color_snake=#f7df1e&color_dots=#bfbdbe&color_ghosts=#ff0000,#ffb8ff,#00ffff,#ffb851&theme=pacman
            dist/pacman-contribution-graph-dark.svg?color_snake=#f7df1e&color_dots=#bfbdbe&color_ghosts=#ff0000,#ffb8ff,#00ffff,#ffb851&theme=pacman

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
